# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-18 21:03
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('racetracks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='racetrack',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
