# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-04 03:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import redactor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('racetracks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', redactor.fields.RedactorField(blank=True, null=True, verbose_name='Description')),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField(blank=True, null=True)),
                ('website', models.URLField(blank=True, max_length=128, null=True)),
                ('racetrack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='racetracks.Racetrack')),
            ],
        ),
    ]
